name: KritikAI code review
description: Automated code reviews for pull requests.

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  kritik-token:
    description: 'KritikAI token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
